# Generated by Django 4.0 on 2025-10-31 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('comment', models.TextField(verbose_name='内容')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真1 (メイン)')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真5')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enright.category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
