# Generated by Django 4.0 on 2025-10-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enright', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真3'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真4'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真5'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真1 (メイン)'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='写真2'),
        ),
    ]
