# Generated by Django 4.0 on 2025-10-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '一般ユーザー'), (2, '要支援者'), (3, '支援者')], default=1, verbose_name='ユーザー種別'),
        ),
    ]
