# Generated by Django 4.0 on 2025-10-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qualification_details',
            field=models.TextField(blank=True, help_text='支援者が所持している資格を記載してください。', null=True, verbose_name='所持資格'),
        ),
    ]
