# Generated by Django 4.0 on 2025-10-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_qualification_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '一般ユーザー'), (2, '要支援者'), (3, '支援者'), (4, '管理者')], default=1, verbose_name='ユーザー種別'),
        ),
    ]
